### ISSUE TITLE
items jump on hover

### ISSUE THREAD

**Issue by Mosquid** [TomerPacific/julOnSale#1]
can be solved by replacing border with `outline` or `box shadow`

**Comment by TomerPacific** [comment]
@Mosquid, you are more than correct. 
Will be implemented.

**Comment by TomerPacific** [comment]
Solved, [Commit](https://github.com/TomerPacific/julOnSale/commit/64e24cc1eea3822fd0a5be3951589748aff85261). Thanks @Mosquid .
